import { useMediaQuery } from "react-responsive";
import AdminpanelContent from "../adminpanelContent";
import AdminpanelContentMobile from "../adminpanelMobile/adminpanelContentMobile";

export default function AdminpanelContentLayout(props) {
  const isMobile = useMediaQuery({
    query: "(max-width: 709px)",
  });
  const isTabAndDesktop = useMediaQuery({
    query: "(min-width: 710px)",
  });

  return (
    <>
      {isMobile && (
        <>
          <AdminpanelContentMobile
            isAgents={props.isAgents}
            setIsAgents={props.setIsAgents}
            isDrivers={props.isDrivers}
            setIsDrivers={props.setIsDrivers}
            isCustomers={props.isCustomers}
            setIsCustomers={props.setIsCustomers}
            isBrokers={props.isBrokers}
            setIsBrokers={props.setIsBrokers}
            isDriverManagers={props.isDriverManagers}
            setIsDriverManagers={props.setIsDriverManagers}
            isShippingCompanies={props.isShippingCompanies}
            setIsShippingCompanies={props.setIsShippingCompanies}
            isTransportCompanies={props.isTransportCompanies}
            setIsTransportCompanies={props.setIsTransportCompanies}
            isClearingForwardingAgent={props.isClearingForwardingAgent}
            setIsClearingForwardingAgent={props.setIsClearingForwardingAgent}
            isSpecializedShipment={props.isSpecializedShipment}
            setIsSpecializedShipment={props.setIsSpecializedShipment}
            isEmployee={props.isEmployee}
            setIsEmployee={props.setIsEmployee}
            isWallet={props.isWallet}
            setIsWallet={props.setIsWallet}
            isWebsite={props.isWebsite}
            setIsWebsite={props.setIsWebsite}
            isLoadboard={props.isLoadboard}
            setIsLoadboard={props.setIsLoadboard}
            isBlog={props.isBlog}
            setIsBlog={props.setIsBlog}
            handleIsAgents={props.handleIsAgents}
            handleIsDrivers={props.handleIsDrivers}
            handleIsCustomers={props.handleIsCustomers}
            handleIsBrokers={props.handleIsBrokers}
            handleIsDriverManagers={props.handleIsDriverManagers}
            handleIsShippingCompanies={props.handleIsShippingCompanies}
            handleIsTransportCompanies={props.handleIsTransportCompanies}
            handleIsClearingForwardingAgent={
              props.handleIsClearingForwardingAgent
            }
            handleIsSpecializedShipment={props.handleIsSpecializedShipment}
            handleIsEmployee={props.handleIsEmployee}
            handleIsWallet={props.handleIsWallet}
            handleIsWebsite={props.handleIsWebsite}
            handleIsLoadboard={props.handleIsLoadboard}
            handleIsBlog={props.handleIsBlog}
            adminAgentData={props.adminAgentData}
            agentList={props.agentList}
            setAgentList={props.setAgentList}
            websiteData={props.websiteData}
            driverList={props.driverList}
            setDriverList={props.setDriverList}
            handleDriverList={props.handleDriverList}
            customerList={props.customerList}
            setCustomerList={props.setCustomerList}
            handleCustomerList={props.handleCustomerList}
            brokerList={props.brokerList}
            setBrokerList={props.setBrokerList}
            handleBrokerList={props.handleBrokerList}
            isOrders={props.isOrders}
            setIsOrders={props.setIsOrders}
            handleIsOrders={props.handleIsOrders}
            isTransactions={props.isTransactions}
            setIsTransactions={props.setIsTransactions}
            handleIsTransactions={props.handleIsTransactions}
            isAdmins={props.isAdmins}
            setIsAdmins={props.setIsAdmins}
            handleIsAdmins={props.handleIsAdmins}
            isPriceSettings={props.isPriceSettings}
            setIsPriceSettings={props.setIsPriceSettings}
            handleIsPriceSettings={props.handleIsPriceSettings}
            addAdmins={props.addAdmins}
            setAddAdmins={props.setAddAdmins}
            adminFullInformation={props.adminFullInformation}
            setAdminFullInformation={props.setAdminFullInformation}
            editAdmins={props.editAdmins}
            setEditAdmins={props.setEditAdmins}
            resetPassword={props.resetPassword}
            setResetPasswword={props.setResetPasswword}
            addsize={props.addsize}
            setAddSize={props.setAddSize}
            editRow={props.editRow}
            setEditRow={props.setEditRow}
            deleteColumn={props.deleteColumn}
            setDeleteColumn={props.setDeleteColumn}
            addDistance={props.addDistance}
            setAddDistance={props.setAddDistance}
            addMiles={props.addMiles}
            setAddMiles={props.setAddMiles}
            addValue={props.addValue}
            setAddValue={props.setAddValue}
            generalEdit={props.generalEdit}
            setGeneralEdit={props.setGeneralEdit}
            isStatistics={props.isStatistics}
            setIsStatistics={props.setIsStatistics}
            handleIsStatistics={props.handleIsStatistics}
          />
        </>
      )}
      {isTabAndDesktop && (
        <>
          <AdminpanelContent
            isAgents={props.isAgents}
            setIsAgents={props.setIsAgents}
            isDrivers={props.isDrivers}
            setIsDrivers={props.setIsDrivers}
            isCustomers={props.isCustomers}
            setIsCustomers={props.setIsCustomers}
            isBrokers={props.isBrokers}
            setIsBrokers={props.setIsBrokers}
            isDriverManagers={props.isDriverManagers}
            setIsDriverManagers={props.setIsDriverManagers}
            isShippingCompanies={props.isShippingCompanies}
            setIsShippingCompanies={props.setIsShippingCompanies}
            isTransportCompanies={props.isTransportCompanies}
            setIsTransportCompanies={props.setIsTransportCompanies}
            isClearingForwardingAgent={props.isClearingForwardingAgent}
            setIsClearingForwardingAgent={props.setIsClearingForwardingAgent}
            isSpecializedShipment={props.isSpecializedShipment}
            setIsSpecializedShipment={props.setIsSpecializedShipment}
            isEmployee={props.isEmployee}
            setIsEmployee={props.setIsEmployee}
            isWallet={props.isWallet}
            setIsWallet={props.setIsWallet}
            isWebsite={props.isWebsite}
            setIsWebsite={props.setIsWebsite}
            isLoadboard={props.isLoadboard}
            setIsLoadboard={props.setIsLoadboard}
            isBlog={props.isBlog}
            setIsBlog={props.setIsBlog}
            handleIsAgents={props.handleIsAgents}
            handleIsDrivers={props.handleIsDrivers}
            handleIsCustomers={props.handleIsCustomers}
            handleIsBrokers={props.handleIsBrokers}
            handleIsDriverManagers={props.handleIsDriverManagers}
            handleIsShippingCompanies={props.handleIsShippingCompanies}
            handleIsTransportCompanies={props.handleIsTransportCompanies}
            handleIsClearingForwardingAgent={
              props.handleIsClearingForwardingAgent
            }
            handleIsSpecializedShipment={props.handleIsSpecializedShipment}
            handleIsEmployee={props.handleIsEmployee}
            handleIsWallet={props.handleIsWallet}
            handleIsWebsite={props.handleIsWebsite}
            handleIsLoadboard={props.handleIsLoadboard}
            handleIsBlog={props.handleIsBlog}
            adminAgentData={props.adminAgentData}
            agentList={props.agentList}
            setAgentList={props.setAgentList}
            handleAgentList={props.handleAgentList}
            editAgentForm={props.editAgentForm}
            setEditAgentForm={props.setEditAgentForm}
            websiteData={props.websiteData}
            setAdminAgentData={props.setAdminAgentData}
            driverList={props.driverList}
            setDriverList={props.setDriverList}
            handleDriverList={props.handleDriverList}
            customerList={props.customerList}
            setCustomerList={props.setCustomerList}
            handleCustomerList={props.handleCustomerList}
            brokerList={props.brokerList}
            setBrokerList={props.setBrokerList}
            handleBrokerList={props.handleBrokerList}
            isOrders={props.isOrders}
            setIsOrders={props.setIsOrders}
            handleIsOrders={props.handleIsOrders}
            isTransactions={props.isTransactions}
            setIsTransactions={props.setIsTransactions}
            handleIsTransactions={props.handleIsTransactions}
            isAdmins={props.isAdmins}
            setIsAdmins={props.setIsAdmins}
            handleIsAdmins={props.handleIsAdmins}
            isPriceSettings={props.isPriceSettings}
            setIsPriceSettings={props.setIsPriceSettings}
            handleIsPriceSettings={props.handleIsPriceSettings}
            addAdmins={props.addAdmins}
            setAddAdmins={props.setAddAdmins}
            adminFullInformation={props.adminFullInformation}
            setAdminFullInformation={props.setAdminFullInformation}
            editAdmins={props.editAdmins}
            setEditAdmins={props.setEditAdmins}
            resetPassword={props.resetPassword}
            setResetPasswword={props.setResetPasswword}
            addsize={props.addsize}
            setAddSize={props.setAddSize}
            editRow={props.editRow}
            setEditRow={props.setEditRow}
            deleteColumn={props.deleteColumn}
            setDeleteColumn={props.setDeleteColumn}
            addDistance={props.addDistance}
            setAddDistance={props.setAddDistance}
            addMiles={props.addMiles}
            setAddMiles={props.setAddMiles}
            addValue={props.addValue}
            setAddValue={props.setAddValue}
            generalEdit={props.generalEdit}
            setGeneralEdit={props.setGeneralEdit}
            isStatistics={props.isStatistics}
            setIsStatistics={props.setIsStatistics}
            handleIsStatistics={props.handleIsStatistics}
          />
        </>
      )}
    </>
  );
}
