export const carouselData = [
  {
    statement1: 'Become a',
    statement2: 'Driver',
    statement3: 'in',
    statement4: 'Monodome',
    statement5: 'Work as a driver and become successful together with Monod.',
    statement6: 'We offer flexible conditions, good earnings and stable income',
    statement7: 'A convenient',
    statement8: 'application for work',
    statement9: 'Payment for work',
    statement10: 'everyday',
    statement11: 'Independent selection',
    statement12: 'of orders for delivery',
    statement13: 'Become a driver',
    statement14: 'Scroll more',
    statement15: 'DRIVER',
    statement16: 'AGENT',
    statement17: 'BUSINESS',
    statement18: 'STUFF',
    statement19: 'SHIPER',
    statement20: 'CARRIER',
    img: '/img/monodomedriver.png',
  },
  {
    statement1: 'Become an',
    statement2: 'AGENT',
    statement3: 'in',
    statement4: 'Monodome',
    statement5: 'Work as a driver and become successful together with Monod.',
    statement6: 'We offer flexible conditions, good earnings and stable income',
    statement7: 'A convenient',
    statement8: 'application for work',
    statement9: 'Payment for work',
    statement10: 'everyday',
    statement11: 'Independent selection',
    statement12: 'of orders for delivery',
    statement13: 'Become an agent',
    statement14: 'Scroll more',
    statement15: 'DRIVER',
    statement16: 'AGENT',
    statement17: 'BUSINESS',
    statement18: 'STUFF',
    statement19: 'SHIPER',
    statement20: 'CARRIER',
    img: '/img/monodomeagentpic.png',
  },
  {
    statement1: 'Start a',
    statement2: 'BUSINESS',
    statement3: 'in',
    statement4: 'Monodome',
    statement5: 'Work as a driver and become successful together with Monod.',
    statement6: 'We offer flexible conditions, good earnings and stable income',
    statement7: 'A convenient',
    statement8: 'application for work',
    statement9: 'Payment for work',
    statement10: 'everyday',
    statement11: 'Independent selection',
    statement12: 'of orders for delivery',
    statement13: 'Start a business',
    statement14: 'Scroll more',
    statement15: 'DRIVER',
    statement16: 'AGENT',
    statement17: 'BUSINESS',
    statement18: 'STUFF',
    statement19: 'SHIPER',
    statement20: 'CARRIER',
    img: '/img/monodomebizpic.png',
  },
  {
    statement1: 'Register as a',
    statement2: 'Clearing and Forwarding Agent',
    statement3: 'in',
    statement4: 'Monodome',
    statement5: 'Work as a driver and become successful together with Monod.',
    statement6: 'We offer flexible conditions, good earnings and stable income',
    statement7: 'A convenient',
    statement8: 'application for work',
    statement9: 'Payment for work',
    statement10: 'everyday',
    statement11: 'Independent selection',
    statement12: 'of orders for delivery',
    statement13: 'Sell with monestate',
    statement14: 'Scroll more',
    statement15: 'DRIVER',
    statement16: 'AGENT',
    statement17: 'BUSINESS',
    statement18: 'STUFF',
    statement19: 'SHIPER',
    statement20: 'CARRIER',
    img: '/img/monodomeclearpic.png',
  },
];

export const appFeatures = [
  {
    imgSrc1: '/img/iphone18one.png',
    imgSrc2: '/img/iphone18two.png',
    caption1: 'Monodome',
    caption2: 'App features',
    desc1:
      'Work as a driver and become successful together with Monod. We offer',
    desc2: 'flexible conditions, good earnings and stable income',
    caption3: 'Notifications',
    caption4: 'GPS Tracking',
    caption5: 'Scheduling',
    caption6: 'Bidding',
    caption7: 'Rating',
    caption8: 'Load board',
    imgSrc3: '/img/monodomenotification.png',
    imgSrc4: '/img/monodomegpstracking.png',
    imgSrc5: '/img/monodomescheduling.png',
    imgSrc6: '/img/monodomebidding.png',
    imgSrc7: '/img/monodomerating.png',
    imgSrc8: '/img/monodomeloadboard.png',
    imgSrc9: '/img/applestoreicon.png',
    imgSrc10: '/img/googleplayicon.png',
  },
  {
    imgSrc1: '/img/iphone18three.png',
    imgSrc2: '/img/iphone18three.png',
    caption1: 'Monodome',
    caption2: 'Load board',
    desc1:
      'Work as a driver and become successful together with Monod. We offer',
    desc2: 'flexible conditions, good earnings and stable income',
    caption3: 'Notifications',
    caption4: 'GPS Tracking',
    caption5: 'Scheduling',
    caption6: 'Bidding',
    caption7: 'Rating',
    caption8: 'Load board',
    imgSrc3: '/img/monodomenotification.png',
    imgSrc4: '/img/monodomegpstracking.png',
    imgSrc5: '/img/monodomescheduling.png',
    imgSrc6: '/img/monodomebidding.png',
    imgSrc7: '/img/monodomerating.png',
    imgSrc8: '/img/monodomeloadboard.png',
    imgSrc9: '/img/applestoreicon.png',
    imgSrc10: '/img/googleplayicon.png',
  },
  {
    imgSrc1: '/img/iphone21one.png',
    imgSrc2: '/img/iphone21two.png',
    caption1: 'Monodome',
    caption2: 'Bidding system',
    desc1:
      'Work as a driver and become successful together with Monod. We offer',
    desc2: 'flexible conditions, good earnings and stable income',
    caption3: 'Notifications',
    caption4: 'GPS Tracking',
    caption5: 'Scheduling',
    caption6: 'Bidding',
    caption7: 'Rating',
    caption8: 'Load board',
    imgSrc3: '/img/monodomenotification.png',
    imgSrc4: '/img/monodomegpstracking.png',
    imgSrc5: '/img/monodomescheduling.png',
    imgSrc6: '/img/monodomebidding.png',
    imgSrc7: '/img/monodomerating.png',
    imgSrc8: '/img/monodomeloadboard.png',
    imgSrc9: '/img/applestoreicon.png',
    imgSrc10: '/img/googleplayicon.png',
  },
];
